### ISSUE TITLE
Notifications are not working

### ISSUE THREAD

**Issue by Veron116** [moshfeu/chrome-extension-notification-demo#3]
I've tried to add notifications to my chrome extension with your tutorial on medium.com, but notifications are not displaing and theren'r any errors.
I cloned your repository and it doesn't work too. Could you help with it?

**Comment by moshfeu** [comment]
Have you changed something in the code, or you tried to run it as is?
Which version of Chrome are you using?

**Comment by Veron116** [comment]
Chrome version is  81.0.4044.122
I tried to run it is.

**Comment by moshfeu** [comment]
In order to see the notification, you need to go to any website (Or just refresh this page when the extension installed). Then, you'll see a button ("Greet me!") in the top left corner. When you click on it, you should see the notification.

![video1](https://user-images.githubusercontent.com/3723951/81202695-a3f58400-8fcf-11ea-9a21-1c568808b07b.gif)

BWY, you should see the extension icon in your icon bar

![Screen Shot 2020-05-06 at 19 29 18](https://user-images.githubusercontent.com/3723951/81202899-e9b24c80-8fcf-11ea-8ae2-7bfe9c09698a.png)
